global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/***'

time_intervals:
  - name: workhours
    time_intervals:
      - times:
        - start_time: 08:20
          end_time: 19:00
        weekdays: ['monday:friday']

route:
  receiver: 'slack'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  group_by: [env]
  routes:
  - receiver: 'slack'
    matchers:
      - env="prod"
    continue: true

  - receiver: 'slack'
    matchers:
      - env="dev"
    group_wait: 1m
    group_interval: 5m
    repeat_interval: 24h
    active_time_intervals:
      - workhours
      #- workdays

receivers:
- name: 'slack'
  slack_configs:
  - channel: '#monitoring-instances'
    send_resolved: true
    icon_url: 'https://avatars3.githubusercontent.com/u/3380462'
    title: |-
     [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
     {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
       {{" "}}(
       {{- with .CommonLabels.Remove .GroupLabels.Names }}
         {{- range $index, $label := .SortedPairs -}}
           {{ if $index }}, {{ end }}
           {{- $label.Name }}="{{ $label.Value -}}"
         {{- end }}
       {{- end -}}
       )
     {{- end }}
    text: >-
     {{ range .Alerts -}}
     *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

     *Description:* {{ .Annotations.description }}

     *Details:*
       {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
       {{ end }}
     {{ end }}
