groups:

- name: info
  rules:
   
  - alert: DEV code is not 200!!!
    expr: sum (http_response_http_response_code{server=~'.*dev.*'} != 200)
            by (server)
    for: 2m
    labels:
      service: www
      severity: warning
      env: dev
    annotations:
      summary: "URL {{ $labels.server }} is DOWN! Status CODE is: {{ $value | printf \"%.2f\" }}"
